### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by victorffrock** [flathub/com.belmoussaoui.Decoder#13]
Is it possible to give the app the ability to read a qr code right from the screen ?

**Comment by A6GibKm** [comment]
For discussions about the app use its gitlab isntance https://gitlab.gnome.org/World/decoder. Otherwise join our matrix channel https://matrix.to/#/#authenticator:gnome.org (yes it is shared with authenticator).

Regarding the question, there is an option to take a screenshot (the implementations depend on your DE, gnome can take a screenshot of a section of the screen) of the screen to look for a qr code already in the app.
